services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports: 
      - "80:80"
    networks:
      - internal
    volumes:
      - ./www/:/srv/www/
      - ./logs/nginx:/var/logs/nginx/
      
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    networks:
      - internal
    volumes:
      - ./www/:/srv/www/

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
